- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdin: true
      stdout: true
      stderr: true

- clean: ['~', '~/.config']

- link:
    ~/.zshrc:
    ~/.bash:
    ~/.bash_logout:
    ~/.bashrc:
    ~/.gitconfig: gitconfig-linux
    ~/.profile:
    ~/.shell:
    ~/.local/bin/: 
        create: true
        glob: true
        path: bin/linux/*
    ~/.local/bin/update-dotfiles: install.sh
    ~/.config/powershell/profile.ps1: pwsh/profile-current-user-all-hosts

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [bash ./dotbot-tools/linux/install/install-after-running-dotbot.sh, Installing software]
